import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@fontsource/syne"; // Default weight (400)
import "@fontsource/syne/600.css"; // Specific weight (600)
import "@fontsource/inter"; // Default weight (400)
import "@fontsource/inter/600.css"; // Specific weight (600)
import "./globals.css";
import {UserContextProvider} from '@/context/userContextProvider'
import { PolicyContextProvider } from "@/context/PolicyContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SCBIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PolicyContextProvider>
          <UserContextProvider>
            {children}
          </UserContextProvider>
        </PolicyContextProvider>
        
      </body>
    </html>
  );
}
